CREATE TABLE "People" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "surname" varchar(200),
  "id_city" integer NOT NULL,
  "control_level" integer NOT NULL DEFAULT 0,
  "role" boolean DEFAULT False
);

CREATE TABLE "City" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL
);

CREATE TABLE "Location" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "id_city" integer NOT NULL,
  "latitude" numeric(10) NOT NULL,
  "longtitude" numeric(10) NOT NULL
);

CREATE TABLE "Powers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "level_accept" integer NOT NULL
);

CREATE TABLE "Machines" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "city_id" integer NOT NULL,
  "location_id" integer NOT NULL,
  "operation_id" integer NOT NULL,
  "level_accept" integer NOT NULL DEFAULT 2,
  "endurance" integer NOT NULL DEFAULT 100,
  "is_it_infrastructure" boolean NOT NULL DEFAULT false
);

CREATE TABLE "Operations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) Not null,
  "location_id" integer NOT NULL,
  "influence" integer NOT NULL DEFAULT 10
);

ALTER TABLE "People" ADD FOREIGN KEY ("id_city") REFERENCES "City" ("id");

ALTER TABLE "Machines" ADD FOREIGN KEY ("city_id") REFERENCES "City" ("id");

ALTER TABLE "Location" ADD FOREIGN KEY ("id_city") REFERENCES "City" ("id");

ALTER TABLE "Machines" ADD FOREIGN KEY ("location_id") REFERENCES "Location" ("id");

ALTER TABLE "Machines"  ADD FOREIGN KEY ("operation_id") REFERENCES "Operations" ("id");

ALTER TABLE "Operations" ADD FOREIGN KEY ("location_id") REFERENCES "Location" ("id");

CREATE TABLE "Powers_Location" (
  "Powers_id" integer,
  "Location_id" integer,
  PRIMARY KEY ("Powers_id", "Location_id")
);

ALTER TABLE "Powers_Location" ADD FOREIGN KEY ("Powers_id") REFERENCES "Powers" ("id");

ALTER TABLE "Powers_Location" ADD FOREIGN KEY ("Location_id") REFERENCES "Location" ("id");


INSERT INTO "City" (name) VALUES ('Диаспар'), ('Курск');
INSERT INTO "People" (name, surname, id_city, control_level) values ('Хедрон', '', 1, 10), ('noname', '', 2, 1);
INSERT INTO "Location" (name, id_city, latitude, longtitude) values ('Котельная', 1, 15.2, 32.3);
INSERT INTO "Powers" (name, level_accept) values ('Fireball', 8), ('Virus', 4), ('Armagedon', 9);
INSERT INTO "Powers_Location" ("Powers_id", "Location_id") values (3, 1);
INSERT INTO "Operations" (name, location_id, influence) values ('Overheating', 1, 10);
INSERT INTO "Machines" (name, city_id, location_id, operation_id, level_accept, is_it_infrastructure) values ('Котёл', 1, 1, 1, 5, true);
SELECT * FROM "People"